server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    serialization:
      write-empty-json-arrays: true
  servlet:
    multipart: #配置文件上传文件大小
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@127.0.0.1:1521/orcl?oracle.jdbc.J2EE13Compliant=true&oracle.jdbc.convertTimestampToUTC=false
          username: TDH
          password: 123456
        HIS:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@127.0.0.1:1521/orcl?oracle.jdbc.J2EE13Compliant=true&oracle.jdbc.convertTimestampToUTC=false
          username: TDH
          password: 123456

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID #不需要手动设置ID，如果手动设置ID，则会使用自己设置的值
  mapper-locations: classpath:com/yin/module/*/mapper/xml/*.xml
